// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_listeProduits = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_listeProduits = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_listeProduits);
    lv_obj_set_width(ui_listeProduits, 189);
    lv_obj_set_height(ui_listeProduits, 280);
    lv_obj_set_x(ui_listeProduits, 3);
    lv_obj_set_y(ui_listeProduits, 3);
    lv_obj_set_align(ui_listeProduits, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_listeProduits, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_listeProduits, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_listeProduits, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_listeProduits, LV_DIR_VER);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_listeProduits = NULL;

}
